### PR TITLE
Added Crud for Tags,User,Entry with Authentication fixes #8, #9, #10

### LINKED ISSUE #8: Form: New Entry
Create a form for a new entry based on entity

### PR DESCRIPTION
**Pull request by aherking**
I would recommend to use the symfony forms - why? Better integration with the other bundles, easier to adapt and highly improveable. I connected the crud function for alle entities, with authentication and role system. We should consume the Symfony documentation to learn how to use these bundles in an advanced way. Writing own functions besides will kill the idea of using a modern Symfony project. Checkout my branch and have a look on it, and if enjoy, merge it :-)

### CODE REVIEW

**Comment by JOverhaus** [comment]
Thought we had already discussed this before, do you have a real reason to go back to the old ways? Symfony forms for me are somehow inefficient and almost impossible to style properly. That was a main reason I requested a change in structure. It would be way better firstly start with showing data, styling the elements we have and then create individual methods to push changes in forms via input fields. This way we always know what is happening and have the complete controll over the looks and functions.

**Comment by aherking** [comment]
There is a very good documentation for customizing the rendering of forms ... You may offer an alternative concept in your branch without using symfony forms so we can compare it, but I think the idea of using this standard bundle is a good way.
https://symfony.com/doc/current/form/form_customization.html

**Comment by aherking** [comment]
The main reason: It's quite better integrated in the symfony structure, and will allow us to make some significant progress while saving time. I still think we should compare both ways.

**Comment by JOverhaus** [comment]
This was the very main reason we broke with the previous concept. I read the documentation already and discussed this with some of the developers. If you really want to do this with symfony forms again do it. But I will not be able to work with this so the templating will be up to you. Doing alternative concepts in different branches means doing the same stuff again in one branch and another branch breaking completely with this. Sorry but this does not seem to spare any time at all. 
Is there a reason we are discussing this and also via github chat function again? Would be way more efficent if you would just tell me.

**Pull request closed without merging**
